apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw9-webserver
  labels:
    app: hw9-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hw9-webserver
  template:
    metadata:
      labels:
        app: hw9-webserver
    spec:
      containers:
      - name: webserver
        image: us-central1-docker.pkg.dev/constant-idiom-485622-f3/hw9-repo/webserver:v1
        ports:
        - containerPort: 8080
        env:
        - name: BUCKET_NAME
          value: "bu-cs528-mahicm13"
        - name: REPORTER_HOST
          value: "10.128.0.18"
        - name: REPORTER_PORT
          value: "9090"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
